### ISSUE TITLE
[NPE] Cannot invoke "me.lulu.biomereplacer.nms.model.biome.BiomeData.name()" because "from" is null

### ISSUE THREAD

**Issue by joex92** [lulu2002/BiomeReplacer#1]
I'm getting this NPE on minecraft 1.17.1:
```yaml
[03:38:21 INFO]: [BiomeReplacer] Enabling BiomeReplacer v1.2.0
[03:38:21 INFO]: Nms Version: v1_17_R1
[03:38:21 ERROR]: Error occurred while enabling BiomeReplacer v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.lulu.biomereplacer.nms.model.biome.BiomeData.name()" because "from" is null
        at me.lulu.biomereplacer.BiomeReplacer.swap(BiomeReplacer.java:76) ~[?:?]
        at me.lulu.biomereplacer.BiomeReplacer.lambda$swapBiomes$0(BiomeReplacer.java:60) ~[?:?]
        at java.util.HashMap.forEach(Unknown Source) ~[?:?]
        at me.lulu.biomereplacer.BiomeReplacer.swapBiomes(BiomeReplacer.java:58) ~[?:?]
        at me.lulu.biomereplacer.BiomeReplacer.onReload(BiomeReplacer.java:38) ~[?:?]
        at me.lulu.biomereplacer.BiomeReplacer.onEnable(BiomeReplacer.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-"a216fc0"]
        at java.lang.Thread.run(Unknown Source) [?:?]
[03:38:21 INFO]: [BiomeReplacer] Disabling BiomeReplacer v1.2.0
```

**Comment by lulu2002** [comment]
Thanks for reporting this issue, could you provide your configuration that cause this problem? thanks!

**Comment by joex92** [comment]
here's the [latest.log](https://github.com/lulu2002/BiomeReplacer/files/6989020/latest.log)
I'm doing some tests to upgrade my server with some worldpainter generated maps...
